# Generated by Django 5.1.4 on 2025-01-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='travelappphoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
