# Generated by Django 5.1.4 on 2025-01-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_post_travelappphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='modifiedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='publishedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
