# Generated by Django 5.1.4 on 2025-02-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0005_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='travelappphoto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='video/'),
        ),
    ]
